version: "3"

services:
  app:
    build: ./.docker
    volumes:
      - ./:/app:delegated

  migration.dev.local:
    image: nginx:1.11
    ports:
      - "80:80"
    volumes:
      - ./:/app:delegated
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
